Administrator.create(:email => 'dave@rapin.com', :password => 'password')

Recommendation.create(:position => 1, :name => "Neil Black", :title => 'CTO', :company => 'ExtendMedia Inc.', :company_url => 'http://www.extend.com', :body => "Dave is an outstanding technical resource who consistently produces high quality technical design and engineering deliverables. He is always curious to try new technologies and methodologies while keeping an eye on the final results. He works well with clients and can explain concepts and solutions in a manner that non-technologists will understand. Dave will always go out of his way to deliver beyond expectations. He has my unqualified recommendation.")
Recommendation.create(:position => 2, :name => "Ethan Dreilinger", :title => 'Executive Producer', :company => 'Cablevision / News', :company_url => 'http://www.news12.com', :body => "For the engagements I had with Dave, I found the level of his work to be above reproach, and his ability to problem solve on the fly to be very impressive. As a client of Dave's it was great that Dave took the time to explain options and cost/benefit to me--and he made sure I understood the issue at hand, my options and his recommendations.")
Recommendation.create(:position => 3, :name => "Burt Heymanson", :title => 'Director of Engineering', :company => 'ClickStar Inc.', :company_url => 'http://www.extend.com', :body => "Dave is a creative engineer, understanding the products he has built and works with amazingly well. His ability to provide seemingly simple solutions to difficult problems in a very timely manner is impressive. I'd work with Dave again anytime, even though he likes bad beer.")
Recommendation.create(:position => 4, :name => "Robinson Kelly", :title => 'CEO and Founder', :company => 'Clay Tablet Technologies Inc.', :company_url => 'http://www.extend.com', :body => "A wunderkind. Smarter than the average Cray - more helpful than a ripcord and shaprer than a tack. I simply love having this guy back on our team.")
Recommendation.create(:position => 5, :name => "Deborah Beatty", :title => 'VP', :company => 'Avid Life Media', :body => "Dave was a pleasure to work with, and produced terrific products. Dave can suggest an approach to any feature build that balances business and usability considerations, and makes sense in terms of an ROI. Dave rebuilt a website for us from scratch, in record time and with minimal managment. He was pro-active in asking questions, suggesting features & improvements, managing infrastructure as well as programming, and providing prioritization. I would certainly try to get Dave on my team again!")
Recommendation.create(:position => 6, :name => "Sean Doyle", :title => 'Chief Systems Architect', :company => 'InfoMedx.com', :body => "Dave is a brilliant and focused engineer, architect and leader. Always competant and trustworthy, he can be relied upon to deliver solid solutions on budget and on time. Dave is a master of building and designing cutting-edge distributed computing solutions, regardless of the environment. Most importantly he always stands behind what he builds and is willing to go the extra mile to ensure success.")
Recommendation.create(:position => 7, :name => "Craig Medland", :title => 'General Manager', :company => 'ExtendMedia Inc.', :company_url => 'http://www.extend.com', :body => "Dave is the rare Software Engineer who delivers software solutions which strike the right balance between competing business, project & technology priorities. Dave accomplishes this via excellent client-facing skills, razor-like focus on delivery and collaborative approach to problem solving (both business & technical). His solutions are practical, clean, easy-to-maintain & scalable. Dave is a great addition to any team due to his optimistic, can-do attitude as well as his keen pride & ownership in his work.")


# http://www.istockphoto.com/stock-photo-14232045-laid-off.php
# http://www.istockphoto.com/stock-photo-13316672-two-men-at-drafting-table.php
# http://www.istockphoto.com/stock-photo-1682647-attention-b-w.php

Project.create(:position => 1, :title => "GrokPhoto - Open-source", :url => "http://grokphoto.com", :intro => "GrokPhoto is an open-source web platform for professional photographers.", :description => "My wife needed a professional photography portfolio site which would allow her to easily manage client galleries, bookings, and photos.\n\nWhile there are plenty of open source galleries out there, most are written in PHP whereas my personal preference is Ruby on Rails. Also, I was unable to find any that supported the more advanced features she needed for managing client photos and workflow.")
Project.create(:position => 2, :title => "Trendex Home", :url => "http://www.trendexhome.com", :intro => "Trendex Home is a custom e-commerce store-front built with Ruby on Rails.", :description => "TrendexHome.com is a custom e-commerce site I built with Ruby on Rails. It includes a custom catalogue of products, with inventory tracking, simplified data entry, shipping integration, on-site payment integration via Beanstream APIs (activemerchant), notifications, and quite a bit of SEO.")
Project.create(:position => 3, :title => "Home Interior Guide", :url => "http://www.homeinteriorguide.com", :intro => "The Home Interior Guide was a complete redesign of an existing PHP site.", :description => "The Home Interior Guide was a complete redesign of an existing PHP site with a limited and mostly static dataset into a much improved Ruby on Rails application.\n\nAll existing listing data was migrated into a new geocoded database making it much easier to maintain customer listings.\n\nAutomated customer sign up and mini-sites were added to further reduce the management effort and increase the value for the customer.")
Project.create(:position => 4, :title => "Clay Tablet Technologies", :url => "http://www.clay-tablet.com", :intro => "B2B translation workflow system for content management applications.", :description => "Clay Tablet manages communication, routing, and workflow between a client's content (usually in a CMS) and a translation provider's system.\n\nProjects and documents flagged for translation are added to the workflow using a custom protocal / xml schema over Amazon's SQS. I was responsible for designing and implementing this framework.\n\nWe built several custom client's for different content management systems as well as generic Java and Ruby clients.")
Project.create(:position => 5, :title => "OpenCASE - ExtendMedia", :url => "http://www.extend.com", :intro => "Over the course of my employment with ExtendMedia I was the lead technical resource for the services of their flagship product offering OpenCASE.\n\nOpenCASE is a media management and workflow system for content providers who want to serve up rich media content like movies and tv shows under a DRM license.")
Project.create(:position => 6, :title => "Jaime Coyle Photography", :url => "http://www.jaimecoyle.com", :intro => "Professional Photography site with secure bookings built using Ruby on Rails.", :description => "I built a fairly simple portfolio, client section, and administration area for this client.\n\nThe following technolgies were used: Ruby on Rails, MySQL, Passenger (mod_rails), Capistrano, Ubuntu Linux, jQuery, Galleria, restlful_authentication, Blueprint CSS.")
Project.create(:position => 7, :title => "Albumdy - Open-source", :url => "http://demo.albumdy.org", :intro => "Albumdy is an open-source minimalist photo gallery built using Ruby on Rails.", :description => "Albumdy is an Opensource project that shows how to build a social photography website with Ruby on Rails and jQuery.\n\nTechnologies used: Ruby on Rails, jQuery, git, Capistrano, MySQL, SWFUpload, Amazon S3, Ubuntu Linux, Blueprint CSS.")
Project.create(:position => 8, :title => "Home Renovation Guide", :url => "http://www.homerenovationguide.com", :intro => "The Home Renovation Guide was a complete redesign of an existing PHP site.", :description => "The Home Renovation Guide was a complete redesign of an existing PHP site with a limited and mostly static dataset into a much improved Ruby on Rails application. Steps includes: Complete graphic redesign by an outside contractor, migration of existing listing and content data, administration portal, new lead generation system, and integrated payment solutions.")

for project in Project.all
  project.image = File.new(File.join(Rails.root, 'photoshop', "#{project.friendly_id}.jpg"))
  project.save
end